### ISSUE TITLE
cannot see the sample files getting classified into sensitive and nonsensitive buckets

### ISSUE THREAD

**Issue by hemantpatil1001** [GoogleCloudPlatform/dlp-cloud-functions-tutorials#1]
I have followed all the steps mentioned in the tutorial link https://cloud.google.com/solutions/automating-classification-of-data-uploaded-to-cloud-storage. Yet i am unable to see the classified data into the respective buckets

**Comment by grapesfrog** [comment]
Sorry I missed this. If it's still a problem please reopen another issue
